### ISSUE TITLE
v0.3 not working on macOS 10.13.2

### ISSUE THREAD

**Issue by felixerdy** [cansik/sweep-processing#5]
When running the BasicExample from v0.3 on macOS 10.13.2 it shows the following error and does not start:
```
java.lang.UnsatisfiedLinkError: Unable to load library 'sweep': Native library (darwin/libsweep.dylib) not found in resource path ([file:/private/var/folders/wd/w9c_7mwx2pj7815jm_xy1yfw0000gn/T/BasicExample332150815667488551temp/, file:/Applications/Processing.app/Contents/Java/core/library/gluegen-rt-natives-linux-armv6hf.jar, file:/Applications/Processing.app/Contents/Java/core/library/jogl-all-natives-linux-armv6hf.jar, file:/Applications/Processing.app/Contents/Java/core/library/gluegen-rt-natives-linux-aarch64.jar, file:/Applications/Processing.app/Contents/Java/core/library/jogl-all-natives-linux-aarch64.jar, file:/Applications/Processing.app/Contents/Java/core/library/gluegen-rt-natives-macosx-universal.jar, file:/Applications/Processing.app/Contents/Java/core/library/gluegen-rt-natives-linux-amd64.jar, file:/Applications/Processing.app/Contents/Java/core/library/jogl-all-natives-linux-i586.jar, file:/Applications/Processing.app/Contents/Java/core/library/gluegen-rt-natives-windows-i586.jar, file:/Applications/Processing.app/Contents/Java/core/library/jogl-all.jar, file:/Applications/Processing.app/Contents/Java/core/library/gluegen-rt-natives-linux-i586.jar, file:/Applications/Processing.app/Contents/Java/core/library/jogl-all-natives-linux-amd64.jar, file:/Applications/Processing.app/Contents/Java/core/library/gluegen-rt.jar, file:/Applications/Processing.app/Contents/Java/core/library/core.jar, file:/Applications/Processing.app/Contents/Java/core/library/jogl-all-natives-macosx-universal.jar, file:/Applications/Processing.app/Contents/Java/core/library/jogl-all-natives-windows-i586.jar, file:/Applications/Processing.app/Contents/Java/core/library/gluegen-rt-natives-windows-amd64.jar, file:/Applications/Processing.app/Contents/Java/core/library/jogl-all-natives-windows-amd64.jar, file:/Users/felix/Documents/Processing/libraries/SweepProcessing/library/jsweep-1.3.0-natives.jar, file:/Users/felix/Documents/Processing/libraries/SweepProcessing/library/SweepProcessing.jar, file:/Users/felix/Documents/Processing/libraries/SweepProcessing/library/jsweep-1.3.0.jar, file:/Users/felix/Documents/Processing/libraries/SweepProcessing/library/jna-4.4.0.jar, file:/Users/felix/Documents/Processing/libraries/SweepProcessing/library/jna-platform-4.4.0.jar, file:/Applications/Processing.app/Contents/Java/, file:/Applications/Processing.app/Contents/Java/ant.jar, file:/Applications/Processing.app/Contents/Java/ant-launcher.jar, file:/Applications/Processing.app/Contents/Java/core.jar, file:/Applications/Processing.app/Contents/Java/jna.jar, file:/Applications/Processing.app/Contents/Java/pde.jar, file:/Applications/Processing.app/Contents/Java/jna-platform.jar])
	at processing.javafx.PSurfaceFX.lambda$0(PSurfaceFX.java:409)
	at java.lang.Thread.run(Thread.java:748)
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.
```

**Comment by cansik** [comment]
Strange, it seems that the native library was not bundled in the release. And on my test system it was working without it (maybe another path). But I will update it as soon as possible.

**Comment by cansik** [comment]
I released a version 0.3.1 with the binary included again. Could you please check if it is working?

**Comment by felixerdy** [comment]
It is now working for me. Thank you! 
Asynchronous start is awesome btw! 👍

**Comment by cansik** [comment]
Great, thank you for the feedback!
